import { RootLayout } from "@/layouts/root";

import { ContextModal } from "@/contexts/modal";

import { HellixVFTRIA, SFProText, VanillaSans } from "./fonts";

import { CookiebotScript } from "./scripts/cookiebot-script";

import { clsx } from "clsx";

import "./globals.css";
import "swiper/css";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Bimaris",
  description: "Generated by create next app",
};

export default function RootLayoutPage({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        {/* Cookiebot */}
        <CookiebotScript />
      </head>

      <body
        className={clsx(
          HellixVFTRIA.variable,
          VanillaSans.variable,
          SFProText.variable,
          "container-variable antialiased",
        )}
      >
        <ContextModal>
          <RootLayout>{children}</RootLayout>
        </ContextModal>
      </body>
    </html>
  );
}
