import { RootLayout } from "@/layouts/root";

import type { Metadata } from "next";

import { HellixVFTRIA, SFProText, VanillaSans } from "./fonts";

import { clsx } from "clsx";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayoutPage({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          HellixVFTRIA.variable,
          VanillaSans.variable,
          SFProText.variable,
          "container-variable antialiased",
        )}
      >
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  );
}
