import { NextIntlClientProvider } from "next-intl";
import { setRequestLocale } from "next-intl/server";

import { RootLayout } from "@/layouts/root";

import { ContextModal } from "@/contexts/modal";

import { HellixVFTRIA, SFProText, VanillaSans } from "../fonts";

import { CookiebotScript } from "../scripts/cookiebot-script";

import { clsx } from "clsx";

import "../globals.css";
import "swiper/css";

import type { Metadata } from "next";

export type RootLayoutPageProps = {
  children: React.ReactNode;
  params: Promise<{
    locale: string;
  }>;
};

export const metadata: Metadata = {
  title: "Bimaris",
  description: "Generated by create next app",
};

export default async function RootLayoutPage({
  children,
  params,
}: Readonly<RootLayoutPageProps>) {
  const { locale } = await params;

  setRequestLocale(locale);

  return (
    <html lang={locale}>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        {/* Cookiebot */}
        <CookiebotScript />
      </head>

      <body
        className={clsx(
          HellixVFTRIA.variable,
          VanillaSans.variable,
          SFProText.variable,
          "container-variable antialiased",
        )}
      >
        <NextIntlClientProvider locale={locale}>
          <ContextModal>
            <RootLayout>{children}</RootLayout>
          </ContextModal>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
